[tool.mypy]
python_version = "3.9"
disallow_untyped_defs = true
ignore_missing_imports = true
follow_imports = "silent"
strict_optional = true
show_error_codes = true
warn_unused_configs = true

[tool.isort]
profile = "black"
line_length = 120
known_first_party = ["src"]
known_third_party = ["pytest", "requests", "flask"]
sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "FIRSTPARTY",
    "LOCALFOLDER"
]
default_section = "THIRDPARTY"
force_sort_within_sections = true

[pep8]
max-line-length = 120

[tool.autopep8]
max-line-length = 120
ignore = ["E402", "W503"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
filterwarnings = [
    "ignore:SOCKS support in urllib3 requires the installation of optional dependencies:urllib3.exceptions.DependencyWarning"
]

[tool.coverage.run]
branch = true
source = ["src"]
omit = [
    "src/*/__init__.py",
    "*/__pycache__/*"
]

[tool.coverage.report]
omit = [
    "src/*/__init__.py",
    "*/__pycache__/*"
]
fail_under = 70
show_missing = true
show_covered = true

[tool.coverage.html]
directory = "coverage_html_report"
title = "Test Coverage Report"

[tool.coverage.xml]
output = "coverage.xml"

[tool.black]
line-length = 120
target-version = ["py38", "py39", "py310"]
